apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  title: Pet Example TF
  name: pet-example-tf
  tags: ['terraform']
  description: The Pet Store Example Terraform
  links:
    - url: https://github.com/Chewy-Inc/pet-tf-tpl
      title: Pet Example Terraform
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: pet-cronus
