apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  title: Pet Example TF
  name: pet-example-tf
  tags: ['terraform']
  description: The Pet Store Example Terraform
spec:
  type: service
  lifecycle: experimental
  owner: pet-cronus
